### ISSUE TITLE
#Wizards: Player pushing spells are very unstable

### ISSUE THREAD

**Issue by chelog** [octothorp-team/sfd#1]
For spells like FusRoDah of To the moon!

**Comment by chelog** [comment]
use SetMass()? I'll try it

**Comment by GeraldDeschain** [comment]
Maybe SetMass has a similar to SpawnFireNodes bug?

**Comment by GeraldDeschain** [comment]
Maybe SetMass has a similar to SpawnFireNodes bug?

**Comment by chelog** [comment]
I'll try to. But if you have any spare time, try to use `IObject.SetMass()` and `IGameHelpers.ConvertMassKGToBox2D()` to make some tests

**Comment by chelog** [comment]
Guys, any ideas? We have three unstable spells:
* fus ro dah
* to the moon
* super jump

**Comment by gwendalaze** [comment]
Well in fact changing mass would not only reduce damage from spells, but would also reduce their push-back....

For me , "to the moon" and "fus roh dah" spells are "almost stable". Moreover, we don't need to make them more stable : actually, loads of player miss spells labeled as "stable", such as "mind lock".

For the super jump i get an idea : what about setting repeatedly and fastly player position to a higher one ? a bit like in my predator mode. It could be added as a part of the "Fast_Tick" method, with a list containing the players casting super jump.

**Comment by chelog** [comment]
@gwendalaze
* about superjump: sure, try it in your branch, please and let me see how it works
* about fus and so on: yeah, I think they're randomly okay now :smile:
* about mind control: I fixed that in some recent updates, now it works pretty well

**Comment by gwendalaze** [comment]
no, super jump won't work as intended...I didn't tougth about it first, but in fact, while a player is in the air, he is accumulating vertical momentum until the moment he reach the ground. That make the fix i proposed a poor one, because instead of fixing an issue, it bring another one.

I tougth about increasing the power of the super jump, but make it uncastable in mid-air (to avoid self-kill). When a player would cast it in mid-air, a PWT message would appear, saying "i can't cast it in mid air!"

**Comment by chelog** [comment]
@gwendalaze, sadly, your version of superjump is really unstable, even more unstable than mine one :laughing:

**Comment by gwendalaze** [comment]
@chelog yeah no. Now it's very stable. Should we let this issue open or close it now ?

**Comment by chelog** [comment]
Eh, well, let's close it, coz we can't do anything until Gurd adds player velocity.
